version: '2'

volumes: 
  mysql-data:

services:
  web:
    image: thecodingmachine/php:7.4-v3-apache
    ports:
      - 8080:80
    volumes: 
      - ./src/:/var/www/html/
    environment: 
      MYSQL_DB: atelier5
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: root

  adminer:
    image: adminer
    environment: 
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8081:8080
    links:
      - mysql
  
  mysql:
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atelier5
    volumes: 
      - mysql-data:/var/lib/mysql