version: '2'

volumes: 
  mysql-data:

services:
  adminer:
    image: adminer
    environment: 
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    links:
      - mysql
  
  mysql:
    image: mysql:5.7
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atelier4
    volumes: 
      - mysql-data:/var/lib/mysql